// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'utils/helper.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 558994816910863526),
    name: 'LevelTestResults',
    lastPropertyId: const obx_int.IdUid(6, 1570814640359703298),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5452915458201226532),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7281914708086593546),
        name: 'CampaignID',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1549321501555700883),
        name: 'MissionID',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7126470332977816987),
        name: 'LevelID',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1628598140301944507),
        name: 'score',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1570814640359703298),
        name: 'timestamp',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 558994816910863526),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    LevelTestResults: obx_int.EntityDefinition<LevelTestResults>(
      model: _entities[0],
      toOneRelations: (LevelTestResults object) => [],
      toManyRelations: (LevelTestResults object) => {},
      getId: (LevelTestResults object) => object.id,
      setId: (LevelTestResults object, int id) {
        object.id = id;
      },
      objectToFB: (LevelTestResults object, fb.Builder fbb) {
        final CampaignIDOffset = fbb.writeString(object.CampaignID);
        final MissionIDOffset = fbb.writeString(object.MissionID);
        final LevelIDOffset = fbb.writeString(object.LevelID);
        final timestampOffset = fbb.writeString(object.timestamp);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, CampaignIDOffset);
        fbb.addOffset(2, MissionIDOffset);
        fbb.addOffset(3, LevelIDOffset);
        fbb.addInt64(4, object.score);
        fbb.addOffset(5, timestampOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final CampaignIDParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final MissionIDParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final LevelIDParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final scoreParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final timestampParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = LevelTestResults(
          id: idParam,
          CampaignID: CampaignIDParam,
          MissionID: MissionIDParam,
          LevelID: LevelIDParam,
          score: scoreParam,
          timestamp: timestampParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [LevelTestResults] entity fields to define ObjectBox queries.
class LevelTestResults_ {
  /// See [LevelTestResults.id].
  static final id = obx.QueryIntegerProperty<LevelTestResults>(
    _entities[0].properties[0],
  );

  /// See [LevelTestResults.CampaignID].
  static final CampaignID = obx.QueryStringProperty<LevelTestResults>(
    _entities[0].properties[1],
  );

  /// See [LevelTestResults.MissionID].
  static final MissionID = obx.QueryStringProperty<LevelTestResults>(
    _entities[0].properties[2],
  );

  /// See [LevelTestResults.LevelID].
  static final LevelID = obx.QueryStringProperty<LevelTestResults>(
    _entities[0].properties[3],
  );

  /// See [LevelTestResults.score].
  static final score = obx.QueryIntegerProperty<LevelTestResults>(
    _entities[0].properties[4],
  );

  /// See [LevelTestResults.timestamp].
  static final timestamp = obx.QueryStringProperty<LevelTestResults>(
    _entities[0].properties[5],
  );
}
