# yml or yaml
#To create a Dart/Flutter application that replicates the functionality of the Melody Ear Trainer, 
#we will need to set up a basic Flutter project structure. Below is the content for the `main.dart` 
#file, which will serve as the entry point for the application. 
#This file will include the necessary imports, a basic UI layout with dropdowns and checkboxes, 
#and functionality for playing notes and chords.

#File: melody.dart

name: melody_ear_trainer_flutter
description: A Flutter application for Melody Ear Training
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: ">=3.0.0 < 5.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  audioplayers: 6.4.0
  just_audio: ^0.9.36

flutter:
  uses-material-design: true
  assets:
    - assets/audio/C-do.mp3
    - assets/audio/C-re.mp3

